version: '3.9'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.133.0
    container_name: otel-collector
    volumes:
      - ./config/config.yaml:/etc/config.yaml # Caminho do arquivo de configuração do OTEL Collector

    command: ["--config", "/etc/config.yaml"]
    ports:
      - "4317:4317"  # gRPC traces
      - "4318:4318"  # HTTP traces/metrics
      - "8888:8888"  # Prometheus scrape endpoint (opcional)
    restart: unless-stopped
