version: '3.9'

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./otelcollectorconfig.yaml:/etc/otelcollectorconfig.yaml # Caminho do arquivo de configuração do OTEL Collector

    command: ["--config", "/etc/otelcollectorconfig.yaml"]
    ports:
      - "4317:4317"  # gRPC traces
      - "4318:4318"  # HTTP traces/metrics
      - "8888:8888"  # Prometheus scrape endpoint (opcional)
    restart: unless-stopped
