global:
  scrape_interval: 15s # A cada 15 segundos, o Prometheus buscará métricas dos alvos.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Adicione outros jobs aqui para monitorar seus outros serviços/aplicações.
  # Exemplo para um node-exporter (se você tivesse um):
  # - job_name: "node"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]