# /prometheus/prometheus.yml
global:
  scrape_interval: 15s # A cada 15 segundos, o Prometheus buscará métricas.

scrape_configs:
  # Job para monitorar o próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # --- MELHOR PRÁTICA COM OPENTELEMETRY ---
  # Em uma arquitetura de observabilidade moderna, suas aplicações enviam métricas
  # para um OpenTelemetry Collector. O Prometheus, então, coleta (scrape) as
  # métricas diretamente do Collector, que as expõe em um formato compatível.
  # Isso centraliza a coleta e o processamento de telemetria.
  #
  # Esta configuração instrui o Prometheus a coletar todas as métricas das suas
  # aplicações a partir do OpenTelemetry Collector.
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889'] # O Prometheus buscará as métricas aqui